# Simple deployment used to deploy and manage the app in muditshukla3/ipl-dashboard:1-RELEASE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
  labels:
    app: grpc-service
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: grpc-service
  template:
    metadata:
      labels:
        app: grpc-service
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: grpc-service-pod
          image: muditshukla3/grpc-server:1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app: grpc-service