grpc:
  client:
    grpc-service:
      address: static://localhost:9999
      negotiationType: plaintext
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: grpc-client
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: admin
        password: admin@123

server:
  port: 9091
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: loggers, health, info
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always